### ISSUE TITLE
Cannot Log In?  HTTPError: 400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by 0bvio** [raffaem/cs-dlp#4]
I cannot seem to get this to work, with the master branch as well as this one.  I keep getting this error, but I've triple checked the login info and it's all good.  I have tried using -n for the .netrc file as well as doing the -u -p option.  What is going on?  ChatGPT was helpful up until this point, we cannot seem to find a work around and I've been at this for HOURS.

C:\Users\CatalystNovus>coursera-dl applying-project-management -n
coursera_dl version 0.11.5
Traceback (most recent call last):
  File "c:\users\catalystnovus\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "c:\users\catalystnovus\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\catalystnovus\.pyenv\pyenv-win\versions\3.8.10\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\catalystnovus\.pyenv\pyenv-win\versions\3.8.10\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\CatalystNovus\.pyenv\pyenv-win\versions\3.8.10\Scripts\coursera-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\catalystnovus\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\coursera\coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "c:\users\catalystnovus\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Desktop (please complete the following information):**
 - OS: Windows (Dual Boot with QubesOS on a separate drive)
 - Browser Firefox
 - Dell OptiPlex 7020 + AMD RX340 + 240GB NVMe m.2 through PCIe adaptor

**Comment by raffaem** [comment]
Please read README
